ecommerce_project/urls.py
import django.contrib.admin
import django.views.generic
from django.urls import include
from django.urls import path

urlpatterns = [
    path('JsKahs8hsdnaKlashjhs6/admin/', django.contrib.admin.site.urls),
    path('', django.views.generic.TemplateView.as_view(template_name='ecommerce/index.html'),
             name='home'),
    path('registration/', include(('registration.urls', 'registration'), namespace='registration')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
]

products/urls.py
from django.urls import path
import products.views

urlpatterns = [
    path('', products.views.index, name='index'),
    path('product/', products.views.product, name='products_product'),
    path('search/', products.views.products_search, name='products_search'),
    path('ajax/action', products.views.product_action, name='product_action')
]

registration/urls.py
import django.conf.urls
from django.urls import path
import registration.views
import django.views.generic

urlpatterns = [
    path('', registration.views.index, name='index'),
    path('signup/', registration.views.signup, name='signup'),
]

products/models.py
import django.db.models


class Search(django.db.models.Model):
    object = django.db.models.Manager()
    id = django.db.models.BigAutoField(primary_key=True)
    text = django.db.models.CharField(max_length=200)
    created_at = django.db.models.DateTimeField(auto_now=True)


class Category(django.db.models.Model):
    objects = django.db.models.Manager()
    id = django.db.models.fields.BigAutoField(primary_key=True)
    name = django.db.models.fields.CharField(max_length=200)

    def __str__(self):
        return u'{0}'.format(self.name)


class Product(django.db.models.Model):
    objects = django.db.models.Manager()
    id = django.db.models.fields.BigAutoField(primary_key=True)
    category = django.db.models.ForeignKey(Category, db_constraint=False, on_delete=django.db.models.CASCADE,
                                           default=None, verbose_name='Category')
    title = django.db.models.CharField(max_length=200)
    description = django.db.models.TextField()
    price = django.db.models.DecimalField(default=0.0, max_digits=10, decimal_places=2)

products/views.py
import django.forms
import django.views.decorators.http
import products.models
import django.http
import products.models
import django.urls
import django.contrib.auth.decorators
import functools


def _ajax_required(func):
    @functools.wraps(func)
    def _wrapped_view(request, *args, **kwargs):
        if request.is_ajax():
            return func(request, *args, **kwargs)
        return django.core.exceptions.PermissionDenied()

    return _wrapped_view


def index(request):
    category = products.models.Category.objects.get(pk=1)
    context = list(products.models.Product.objects.filter(category_id=category.id).values())
    return django.http.response.JsonResponse(data=context, safe=False)


@django.views.decorators.http.require_POST
def products_search(request):
    if request.POST.get('search_string'):
        search_data = products.models.Search()
        search_data.text = request.POST.get('search_string')
        search_data.save()
    return django.http.HttpResponseRedirect(django.urls.reverse('home'))


class Actions:
    ADD = 'add'
    UPDATE = 'update'
    DELETE = 'delete'

    def __init__(self, request):
        self.request = request

    def add(self):
        _product = products.models.Product()
        _product.title = self.request.POST.get('title')
        _product.category.id = self.request.POST.get('category_id')
        _product.description = self.request.POST.get('description')
        _product.save()

    def update(self):
        pass

    def delete(self):
        pass


class ProductsForm(django.forms.ModelForm):
    category = django.forms.ModelChoiceField(
        queryset=products.models.Category.objects.all())

    class Meta:
        model = products.models.Product
        fields = '__all__'
        # widgets = {'added_by': django.forms.HiddenInput()}


@_ajax_required
@django.views.decorators.http.require_POST
def product_action(request):
    request_action = request.POST.get('action')
    action_ = Actions(request)
    if request_action == Actions.ADD:
        action_.add()
    elif request_action == Actions.UPDATE:
        action_.update()
    elif request_action == Actions.DELETE:
        action_.delete()


def product(request):
    initial_form_data = {}
    if request.method == 'GET':
        return django.shortcuts.render(request, 'products/index.html',
                                       context={'form': ProductsForm(initial=initial_form_data)})
    if request.method == "POST":
        data = request.POST.dict()
        form = ProductsForm(data, initial=initial_form_data)
        if not form.is_valid():
            return django.shortcuts.render(request, 'products/index.html',
                                           context={'form': ProductsForm(initial=initial_form_data)})
        initial_form_data['success'] = 'true'
        form.save()
        return django.shortcuts.render(request, 'products/index.html',
                                       context={'form': ProductsForm(initial=initial_form_data)})

templates/ecommerce/index.html
{% load static bootstrap4 %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_css %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Moora! Buy products in very LOW price.</title>
</head>
<body>
<div class="topnav">
  <div class="topnav-right">
    <a href="#search">Start Selling</a>
    <a href="#Track">Track Order</a>
    <a href="#Signup">Sign Up</a>
    <a href="#Login">Log In</a>
  </div>
</div>
<div class="header_top">
        <div class="row">
            <div class="col-2">
                <img src="{% static 'images/logo-100px.png' %}" alt="" class="img-fluid topleft">
            </div>
            <div class="search-container col-10">
                <form action="{% url 'products:products_search' %}"method="post" autocomplete="off">
                     {% csrf_token %}
                      <input type="text" placeholder="Search for products" name="search_string">
                       <button type="submit"><i class="fa fa-search"></i></button>
                       <button type="submit" class="ml-1"><i class="fa fa-shopping-cart"></i></button>

                </form>
            </div>
        </div>

</div>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</body>
</html>

templates/products/index.html
{% load static bootstrap4 %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_css %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <h4>Products</h4>
</head>
<body>
<div class="row">
        <div class="col-12 mt-5 form-group">
            {% bootstrap_messages %}
            <form action="{% url 'products:products_product'%}" id="product_action" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                <div class="float text-center">
                    <button type="submit" class="btn btn-primary col-6">Submit</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>